##  ETE

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('C:/Users\priya\Downloads\DATA.csv')

In [4]:
df.head()

Date         ITC      INFOSYS        NIFTY
0  18-11-2020  174.923737  1089.042603  12938.25000
1  19-11-2020  178.582825  1075.509766  12771.70020
2  20-11-2020  182.194397  1081.981812  12859.04981
3  23-11-2020  181.386551  1117.775024  12926.45020
4  24-11-2020  185.853500  1117.971313  13055.15039

In [56]:
df['%_ITC_daily_rturn'] = (df['ITC']-df['ITC'].shift(1))/df['ITC']*100
df['%_INFOSYS_daily_rturn'] = (df['INFOSYS']-df['INFOSYS'].shift(1))/df['INFOSYS']*100
df['%_NIFTY_daily_rturn'] = (df['NIFTY']-df['NIFTY'].shift(1))/df['NIFTY']*100

In [58]:
df['ITC_daily_change'] = df['ITC']-df['ITC'].shift(1)
df['INFOSYS_daily_change'] = df['INFOSYS']-df['INFOSYS'].shift(1)
df['NIFTY_daily_change'] = df['NIFTY']-df['NIFTY'].shift(1)

In [60]:
df.head()

Date         ITC      INFOSYS        NIFTY  %_ITC_daily_rturn  \
0  18-11-2020  174.923737  1089.042603  12938.25000                NaN   
1  19-11-2020  178.582825  1075.509766  12771.70020           2.048959   
2  20-11-2020  182.194397  1081.981812  12859.04981           1.982263   
3  23-11-2020  181.386551  1117.775024  12926.45020          -0.445373   
4  24-11-2020  185.853500  1117.971313  13055.15039           2.403479   

   %_INFOSYS_daily_rturn  %_NIFTY_daily_rturn  ITC_daily_change  \
0                    NaN                  NaN               NaN   
1              -1.258272            -1.304053          3.659088   
2               0.598166             0.679285          3.611572   
3               3.202184             0.521415         -0.807846   
4               0.017558             0.985819          4.466949   

   INFOSYS_daily_change  NIFTY_daily_change  
0                   NaN                 NaN  
1            -13.532837          -166.54980  
2              6.472046            87.34961  
3             35.793212            67.40039  
4              0.196289           128.70019

In [22]:
## creating array of daily return of ITC,INFOSYS , NIFTY

ITC_daily_rturn = (df['ITC']-df['ITC'].shift(1)).dropna()
INFOSYS_daily_rturn  = (df['INFOSYS']-df['INFOSYS'].shift(1)).dropna()
NIFTY_daily_rturn = (df['NIFTY']-df['NIFTY'].shift(1)).dropna()

In [46]:
## Mean of daily return / expected daily ruturn
mean_ITC_daily_rturn = np.mean(ITC_daily_rturn)
mean_INFOSYS_daily_rturn = np.mean(INFOSYS_daily_rturn)
mean_NIFTY_daily_rturn = np.mean(NIFTY_daily_rturn)

In [50]:
mean_INFOSYS_daily_rturn

2.8177853918367344

In [42]:
ITC_daily_rturn_lag

2      3.659088
3      3.611572
4     -0.807846
5      4.466949
6     -1.615692
         ...   
241   -0.850006
242    2.899994
243    5.200012
244   -2.650009
245    4.050003
Name: ITC, Length: 244, dtype: float64

# Q2  calculate all possible correlations, covariances and variances of returns for INFOSYS, ITC and NIFTY

In [24]:
## Finding mean of given data
def mean_value(data) :
    return np.mean(data)

## finding standard deviation of data
def std_dev(data) :
    mean_data_sqr = mean_value(data**2)
    sqr_mean_value = mean_value(data)**2
    return np.sqrt(mean_data_sqr-sqr_mean_value)

## finding variance of data
def variance_data(data) :
    mean_data_sqr = mean_value(data**2)
    sqr_mean_value = mean_value(data)*mean_value(data)
    return np.sqrt(mean_data_sqr-sqr_mean_value)

## finding coveriance between given data1 and data2
def cov_variance_data(data1, data2) :
    cov_variance = mean_value(data1*data2)- mean_value(data1)*mean_value(data2)
    return   cov_variance

## finding correlation between given data1 and data2
def correlation(data1, data2) :
    cov_variance = mean_value(data1*data2)- mean_value(data1)*mean_value(data2)
    
    return   cov_variance/(std_dev(data1)*std_dev(data2))


In [25]:
## finding Variance 
print('vatinace of rturn for ITC',variance_data(ITC_daily_rturn) )
print('vatinace of rturn for INFOSYS',variance_data(INFOSYS_daily_rturn) )
print('vatinace of rturn for NIFTY',variance_data(NIFTY_daily_rturn) )

vatinace of rturn for ITC 3.4739412728802836
vatinace of rturn for INFOSYS 19.10528806650599
vatinace of rturn for NIFTY 144.37179187350208


In [30]:
## Finding correlation 
print('correlation between ITC and infosis', correlation(ITC_daily_rturn,INFOSYS_daily_rturn ))
print('correlation  between ITC and Nifty', correlation(ITC_daily_rturn,NIFTY_daily_rturn))
print('correlation between  infosis and Nifty', correlation(INFOSYS_daily_rturn,NIFTY_daily_rturn))


correlation between ITC and infosis 0.15207869652312314
correlation  between ITC and Nifty 0.47004937726703816
correlation between  infosis and Nifty 0.5245291797011794


In [31]:
## finding covariance
print('covariance between ITC and infosis',cov_variance_data(ITC_daily_rturn,INFOSYS_daily_rturn ))
print('covariance  between ITC and Nifty',cov_variance_data(ITC_daily_rturn,NIFTY_daily_rturn))
print('covariance between  infosis and Nifty',cov_variance_data(INFOSYS_daily_rturn,NIFTY_daily_rturn))


covariance between ITC and infosis 10.093561748457972
covariance  between ITC and Nifty 235.74815405302513
covariance between  infosis and Nifty 1446.79030602368


## Q3 finding Auto correlation

In [35]:
import statsmodels.api as sm

In [85]:
## AUTOCORRELATION VALUE FOR ITC FOR DIFFERNT LAG
ITC_autocorrelation = np.correlate(ITC_daily_rturn,ITC_daily_rturn, mode="full")

In [87]:
ITC_autocorrelation

array([-7.31817600e+00,  7.59617338e+00,  6.54595330e+00, -2.74907352e+00,
        5.28548910e+01, -1.70242870e+01,  3.56239197e+01,  7.36587494e-01,
        2.04552560e+01,  2.71579775e+01, -3.69449184e+01,  5.61267294e+01,
       -1.70121080e+00, -6.13207645e+01, -1.46834283e+00,  4.36952017e+01,
       -3.58995179e+01,  2.25531913e+01,  2.59731864e+00,  4.90127143e+01,
       -1.31881627e+02, -9.63022035e+00,  6.75315114e+01, -2.89706367e+01,
       -2.42383309e+01,  3.35058327e+00,  7.25950795e+01, -1.48649351e+02,
       -4.90628286e+01, -8.30878956e+01,  5.67278268e+01, -1.27889729e+02,
       -2.34424531e+01,  2.66068444e+01,  8.42736297e+01, -2.89855330e+01,
       -9.36146815e+00,  1.53379747e+02,  1.34122957e+02,  1.51659484e+01,
        2.20068885e+01,  2.22301876e+02, -7.50733408e+01, -8.15430839e+01,
        2.81989589e+01,  6.54785125e+01, -9.88454156e+01,  4.42825693e+01,
        2.70506017e+01,  2.95721923e+01,  1.42225955e+01,  6.69597624e+01,
        7.67216488e+01,  

In [91]:
# ## AUTOCORRELATION VALUE FOR Infosys FOR DIFFERNT LAG
iNFOSYS_autocorrelation = np.correlate(INFOSYS_daily_rturn,INFOSYS_daily_rturn, mode="full")
iNFOSYS_autocorrelation

array([ 1.08938350e+02,  1.35360878e+01, -3.89217250e+02, -2.35903704e+02,
       -2.13709073e+02,  7.81406559e+02,  1.66015801e+03, -7.33529221e+02,
       -1.93640431e+03,  5.94742951e+02,  1.05557467e+03,  1.27489776e+03,
       -4.87744179e+02,  1.10808501e+02, -1.48636595e+03,  2.29702340e+02,
        2.65206768e+03,  1.44258909e+03,  8.03137943e+02, -2.33113477e+03,
       -3.46727180e+03,  1.05655301e+03,  3.89223414e+03,  1.58064863e+03,
        8.59221641e+02, -3.56523954e+03,  1.92337999e+02,  7.50999815e+02,
        3.57114398e+03,  8.18773545e+01, -1.15062103e+03,  2.35887869e+03,
       -6.45155085e+02,  4.38748833e+03,  2.78979351e+03, -4.60188711e+03,
       -6.80618915e+02,  3.93914260e+03,  1.74749240e+03, -2.62928511e+02,
       -5.50969129e+02, -7.43452025e+02, -1.38865571e+03,  2.87368659e+03,
        6.46248542e+03, -5.67895034e+02, -4.22863596e+03, -4.69497129e+03,
       -7.35613337e+02,  4.29604529e+03,  9.70365199e+02, -2.59770669e+03,
       -3.40774051e+02, -

In [92]:
## AUTOCORRELATION VALUE FOR Nifty FOR DIFFERNT LAG
Nifty_autocorrelation = np.correlate(NIFTY_daily_rturn,NIFTY_daily_rturn, mode="full")
Nifty_autocorrelation

array([ 2.22926258e+04,  5.05467629e+03,  5.57698448e+02, -3.47495488e+04,
       -3.16164131e+04,  3.27649923e+04,  1.94460545e+04, -1.09361264e+04,
       -1.19240950e+05,  6.47245454e+04, -2.10062378e+04, -1.14830323e+04,
       -5.41159662e+04,  6.61299586e+04,  7.16994998e+03, -1.08642423e+05,
        1.22465866e+04,  6.37787004e+04,  6.53038862e+03, -3.34598733e+04,
       -6.54957211e+04,  5.28718829e+04,  7.06519966e+03, -2.55244959e+04,
       -3.68863115e+04, -2.07448195e+05,  3.74845329e+04, -1.22712114e+04,
        7.58589596e+04, -1.54630276e+05, -1.48364574e+04, -1.24506490e+04,
       -1.76212728e+04,  1.63192541e+05,  1.72916587e+05, -7.12511881e+04,
       -1.10986256e+05, -6.24509518e+03,  6.27641530e+04,  2.47144339e+04,
        2.04427116e+05, -4.17168852e+04, -1.71534215e+05, -1.81414683e+05,
        2.24512948e+05,  1.43473074e+05, -5.32193558e+04, -9.12882048e+04,
        5.57707347e+04,  2.34511159e+04, -1.56433052e+05, -5.50688899e+04,
        3.14046854e+05, -

## 4.Minimum variance portfolio: Portfolio weights

In [67]:
itc_mean_daily_rturn=np.mean(df['%_ITC_daily_rturn'])
INFOSYS_mean_daily_rturn = np.mean(df['%_INFOSYS_daily_rturn'])
nifty_daily_rturn = np.mean(df['%_NIFTY_daily_rturn'] )

In [68]:
itc_rturn_var=np.var(df['%_ITC_daily_rturn'])
INFOSYS_rturn_var = np.var(df['%_INFOSYS_daily_rturn'])
nifty_rturn_var = np.var(df['%_NIFTY_daily_rturn'] )

In [70]:
max(itc_mean_daily_rturn,INFOSYS_mean_daily_rturn,nifty_daily_rturn)

0.19125473433858783

In [71]:
min(itc_mean_daily_rturn,INFOSYS_mean_daily_rturn,nifty_daily_rturn)

0.1118541112786986

In [74]:
print('itc, infosis, nifty expected daily return ;',itc_mean_daily_rturn,INFOSYS_mean_daily_rturn,nifty_daily_rturn)

itc, infosis, nifty expected daily return ; 0.1118541112786986 0.19125473433858783 0.12469901248160153


In [73]:
print('itc, infosis, nifty variance ;',itc_rturn_var,INFOSYS_rturn_var,nifty_rturn_var)

itc, infosis, nifty variance ; 2.5761790164712646 1.7793151499335367 0.9244980241609653


In [78]:
df[['%_ITC_daily_rturn','%_INFOSYS_daily_rturn','%_NIFTY_daily_rturn']].corr()

%_ITC_daily_rturn  %_INFOSYS_daily_rturn  \
%_ITC_daily_rturn               1.000000               0.153797   
%_INFOSYS_daily_rturn           0.153797               1.000000   
%_NIFTY_daily_rturn             0.476764               0.533007   

                       %_NIFTY_daily_rturn  
%_ITC_daily_rturn                 0.476764  
%_INFOSYS_daily_rturn             0.533007  
%_NIFTY_daily_rturn               1.000000